/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author shahd
 */
public class CreateJPanel extends javax.swing.JPanel {
    //To create a Referrence of Car class
    Car car;
    String filename;
    /**
     * Creates new form createJpanel
     */
    public CreateJPanel(Car car) {
        initComponents();
        //Initalization of Car referrence with the referrence passed in the constructor
        this.car=car;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        car1 = new Business.Car();
        productLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        transmissionLabel = new javax.swing.JLabel();
        colourLabel = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();
        seatingCapacityLabel = new javax.swing.JLabel();
        horsepowerLabel = new javax.swing.JLabel();
        fuelTankCapacityLabel = new javax.swing.JLabel();
        fuelEcomonyLabel = new javax.swing.JLabel();
        serialNumberLabel = new javax.swing.JLabel();
        cruiseControlLabel = new javax.swing.JLabel();
        maxSpeedLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        bootSpaceLabel = new javax.swing.JLabel();
        bodyMaterialLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        modeltxtField = new javax.swing.JTextField();
        transmissionTxtField = new javax.swing.JTextField();
        colourTxtField = new javax.swing.JTextField();
        engineTxtField = new javax.swing.JTextField();
        seatingCapacityTxtField = new javax.swing.JTextField();
        horsePowerTxtField = new javax.swing.JTextField();
        fuelTankCapacityTxtField = new javax.swing.JTextField();
        fuelEconomyTxtField = new javax.swing.JTextField();
        serialNumberTxtField = new javax.swing.JTextField();
        cruiseControlTxtField = new javax.swing.JTextField();
        maxSpeedTxtField = new javax.swing.JTextField();
        BrandTxtField = new javax.swing.JTextField();
        bootSpaceTxtField = new javax.swing.JTextField();
        bodyMaterialTxtField = new javax.swing.JTextField();
        accelerationTxtField = new javax.swing.JTextField();
        createcarbutton = new javax.swing.JButton();
        Jfileupload = new javax.swing.JButton();
        pathName = new javax.swing.JLabel();

        productLabel.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        productLabel.setForeground(new java.awt.Color(255, 0, 0));
        productLabel.setText("Create your Car");

        modelLabel.setText("Model");

        transmissionLabel.setText("Transmission");

        colourLabel.setText("Colour");

        engineLabel.setText("Engine");

        seatingCapacityLabel.setText("Seating Capacity");

        horsepowerLabel.setText("Horsepower");

        fuelTankCapacityLabel.setText("Fuel Tank Capacity");

        fuelEcomonyLabel.setText("Fuel Economy");

        serialNumberLabel.setText("Serial Number");

        cruiseControlLabel.setText("Cruise Control");

        maxSpeedLabel.setText("Max Speed");

        brandLabel.setText("Brand");

        bootSpaceLabel.setText("Boot Space");

        bodyMaterialLabel.setText("Body Material");

        accelerationLabel.setText("Acceleration");

        createcarbutton.setText("CREATE");
        createcarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createcarbuttonActionPerformed(evt);
            }
        });

        Jfileupload.setText("Upload Image");
        Jfileupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JfileuploadActionPerformed(evt);
            }
        });

        pathName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pathName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelTankCapacityLabel)
                            .addComponent(fuelEcomonyLabel)
                            .addComponent(serialNumberLabel)
                            .addComponent(cruiseControlLabel)
                            .addComponent(bootSpaceLabel)
                            .addComponent(bodyMaterialLabel)
                            .addComponent(accelerationLabel)
                            .addComponent(maxSpeedLabel)
                            .addComponent(brandLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelTankCapacityTxtField)
                            .addComponent(fuelEconomyTxtField)
                            .addComponent(serialNumberTxtField)
                            .addComponent(cruiseControlTxtField)
                            .addComponent(maxSpeedTxtField)
                            .addComponent(BrandTxtField)
                            .addComponent(bootSpaceTxtField)
                            .addComponent(bodyMaterialTxtField)
                            .addComponent(accelerationTxtField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel)
                            .addComponent(colourLabel)
                            .addComponent(transmissionLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transmissionTxtField)
                            .addComponent(colourTxtField)
                            .addComponent(modeltxtField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engineLabel)
                            .addComponent(seatingCapacityLabel)
                            .addComponent(horsepowerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatingCapacityTxtField)
                            .addComponent(engineTxtField)
                            .addComponent(horsePowerTxtField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pathName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(productLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jfileupload))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(createcarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modeltxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transmissionLabel)
                    .addComponent(transmissionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourLabel)
                    .addComponent(colourTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(engineLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(engineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatingCapacityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horsePowerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horsepowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelTankCapacityLabel)
                    .addComponent(fuelTankCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelEcomonyLabel)
                    .addComponent(fuelEconomyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumberLabel)
                    .addComponent(serialNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cruiseControlLabel)
                    .addComponent(cruiseControlTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxSpeedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxSpeedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(BrandTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bootSpaceLabel)
                    .addComponent(bootSpaceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyMaterialLabel)
                    .addComponent(bodyMaterialTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accelerationLabel)
                    .addComponent(accelerationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Jfileupload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pathName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createcarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createcarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createcarbuttonActionPerformed
        // TODO add your handling code here:
        
        
        //To take input from user and set the variables of car object
        car.setModelName(modeltxtField.getText());
        car.setTransmission(transmissionTxtField.getText());
        car.setEngine(engineTxtField.getText());
        car.setColour(colourTxtField.getText());
        car.setSeatingCapacity(seatingCapacityTxtField.getText());
        car.setFuelTankCapacity(fuelTankCapacityTxtField.getText());
        car.setFuelEconomy(fuelEconomyTxtField.getText());
        car.setHorsePower(horsePowerTxtField.getText());
        car.setSerialNumber(serialNumberTxtField.getText());
        car.setCruiseControl(cruiseControlTxtField.getText());
        car.setMaxSpeed(maxSpeedTxtField.getText());
        car.setAcceleration(accelerationTxtField.getText());
        car.setBrand(BrandTxtField.getText());
        car.setBootSpace(bootSpaceTxtField.getText());
        car.setBodymat(bodyMaterialTxtField.getText());
        car.setCarImagePath(filename);
        //To create message dailog on successful creation of Car
        JOptionPane.showMessageDialog(null,"Your Car has been Created Successfully","Confirmation Message",JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_createcarbuttonActionPerformed

    private void JfileuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JfileuploadActionPerformed
        
        //To select an image file from user's machine and set the imagePath variable
        //Filter is used to only allow image files to be uploaded
        //Error message will be displayed when user cancels the dialog without selecting the file.
        
        JFileChooser choose = new JFileChooser();
        choose.setDialogTitle("Please Select an Image of your Car");
        choose.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filt = new FileNameExtensionFilter("Image Files ONLY","PNG","JPG","JPEG");
        choose.addChoosableFileFilter(filt);
        int r=choose.showOpenDialog(null);
        File f=choose.getSelectedFile();
        
        if ( r == JFileChooser.APPROVE_OPTION){
           filename=f.getAbsolutePath();
        }else
            JOptionPane.showMessageDialog(null,"Please select a File to Upload","Error",JOptionPane.INFORMATION_MESSAGE);
        
        pathName.setText(choose.getSelectedFile().getName());
        
    }//GEN-LAST:event_JfileuploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandTxtField;
    private javax.swing.JButton Jfileupload;
    private javax.swing.JLabel accelerationLabel;
    private javax.swing.JTextField accelerationTxtField;
    private javax.swing.JLabel bodyMaterialLabel;
    private javax.swing.JTextField bodyMaterialTxtField;
    private javax.swing.JLabel bootSpaceLabel;
    private javax.swing.JTextField bootSpaceTxtField;
    private javax.swing.JLabel brandLabel;
    private Business.Car car1;
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTxtField;
    private javax.swing.JButton createcarbutton;
    private javax.swing.JLabel cruiseControlLabel;
    private javax.swing.JTextField cruiseControlTxtField;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JTextField engineTxtField;
    private javax.swing.JLabel fuelEcomonyLabel;
    private javax.swing.JTextField fuelEconomyTxtField;
    private javax.swing.JLabel fuelTankCapacityLabel;
    private javax.swing.JTextField fuelTankCapacityTxtField;
    private javax.swing.JTextField horsePowerTxtField;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JLabel maxSpeedLabel;
    private javax.swing.JTextField maxSpeedTxtField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modeltxtField;
    private javax.swing.JLabel pathName;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel seatingCapacityLabel;
    private javax.swing.JTextField seatingCapacityTxtField;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JTextField serialNumberTxtField;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JTextField transmissionTxtField;
    // End of variables declaration//GEN-END:variables
}
