/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author shahd
 */
public class ViewJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form viewJpanel
     */
    public ViewJPanel( Car car) {
        
        initComponents();
        
        //get the value from variable in Car object and display it in the Jpanel 
        carImageLabel.setSize(650, 450);
        modeltxtField.setText(car.getModelName());
        transmissionTxtField.setText(car.getTransmission());
        engineTxtField.setText(car.getEngine());
        colourTxtField.setText(car.getColour());
        seatingCapacityTxtField.setText(car.getSeatingCapacity());
        fuelTankCapacityTxtField.setText(car.getFuelTankCapacity());
        fuelEconomyTxtField.setText(car.getFuelEconomy());
        horsePowerTxtField.setText(car.getHorsePower());
        serialNumberTxtField.setText(car.getSerialNumber());
        cruiseControlTxtField.setText(car.getCruiseControl());
        maxSpeedTxtField.setText(car.getMaxSpeed());
        accelerationTxtField.setText(car.getAcceleration());
        BrandTxtField.setText(car.getBrand());
        bootSpaceTxtField.setText(car.getBootSpace());
        bodyMaterialTxtField.setText(car.getBodymat());
        
        //To set image on the Jlabel and display it after scaling it
        ImageIcon icon= new ImageIcon(car.getCarImagePath());
        Image icon2=icon.getImage();
        Image icon3=icon2.getScaledInstance(carImageLabel.getWidth(),carImageLabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon finalIcon = new ImageIcon(icon3);
        carImageLabel.setIcon(finalIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        cruiseControlLabel = new javax.swing.JLabel();
        bootSpaceTxtField = new javax.swing.JTextField();
        maxSpeedLabel = new javax.swing.JLabel();
        bodyMaterialTxtField = new javax.swing.JTextField();
        brandLabel = new javax.swing.JLabel();
        accelerationTxtField = new javax.swing.JTextField();
        bootSpaceLabel = new javax.swing.JLabel();
        bodyMaterialLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        modeltxtField = new javax.swing.JTextField();
        transmissionTxtField = new javax.swing.JTextField();
        productLabel = new javax.swing.JLabel();
        colourTxtField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        engineTxtField = new javax.swing.JTextField();
        transmissionLabel = new javax.swing.JLabel();
        seatingCapacityTxtField = new javax.swing.JTextField();
        colourLabel = new javax.swing.JLabel();
        horsePowerTxtField = new javax.swing.JTextField();
        engineLabel = new javax.swing.JLabel();
        fuelTankCapacityTxtField = new javax.swing.JTextField();
        seatingCapacityLabel = new javax.swing.JLabel();
        fuelEconomyTxtField = new javax.swing.JTextField();
        horsepowerLabel = new javax.swing.JLabel();
        fuelTankCapacityLabel = new javax.swing.JLabel();
        serialNumberTxtField = new javax.swing.JTextField();
        cruiseControlTxtField = new javax.swing.JTextField();
        fuelEcomonyLabel = new javax.swing.JLabel();
        maxSpeedTxtField = new javax.swing.JTextField();
        serialNumberLabel = new javax.swing.JLabel();
        BrandTxtField = new javax.swing.JTextField();
        carImageLabel = new javax.swing.JLabel();

        image.setBorder(new javax.swing.border.MatteBorder(null));

        image1.setBorder(new javax.swing.border.MatteBorder(null));

        cruiseControlLabel.setText("Cruise Control");

        bootSpaceTxtField.setEditable(false);

        maxSpeedLabel.setText("Max Speed");

        bodyMaterialTxtField.setEditable(false);

        brandLabel.setText("Brand");

        accelerationTxtField.setEditable(false);

        bootSpaceLabel.setText("Boot Space");

        bodyMaterialLabel.setText("Body Material");

        accelerationLabel.setText("Acceleration");

        modeltxtField.setEditable(false);

        transmissionTxtField.setEditable(false);

        productLabel.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        productLabel.setForeground(new java.awt.Color(255, 0, 0));
        productLabel.setText("            View Your Car");

        colourTxtField.setEditable(false);

        modelLabel.setText("Model");

        engineTxtField.setEditable(false);

        transmissionLabel.setText("Transmission");

        seatingCapacityTxtField.setEditable(false);

        colourLabel.setText("Colour");

        horsePowerTxtField.setEditable(false);

        engineLabel.setText("Engine");

        fuelTankCapacityTxtField.setEditable(false);

        seatingCapacityLabel.setText("Seating Capacity");

        fuelEconomyTxtField.setEditable(false);

        horsepowerLabel.setText("Horsepower");

        fuelTankCapacityLabel.setText("Fuel Tank Capacity");

        serialNumberTxtField.setEditable(false);

        cruiseControlTxtField.setEditable(false);

        fuelEcomonyLabel.setText("Fuel Economy");

        maxSpeedTxtField.setEditable(false);

        serialNumberLabel.setText("Serial Number");

        BrandTxtField.setEditable(false);

        carImageLabel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelTankCapacityLabel)
                            .addComponent(fuelEcomonyLabel)
                            .addComponent(serialNumberLabel)
                            .addComponent(cruiseControlLabel)
                            .addComponent(bootSpaceLabel)
                            .addComponent(bodyMaterialLabel)
                            .addComponent(accelerationLabel)
                            .addComponent(maxSpeedLabel)
                            .addComponent(brandLabel)
                            .addComponent(horsepowerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bodyMaterialTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(bootSpaceTxtField)
                            .addComponent(BrandTxtField)
                            .addComponent(maxSpeedTxtField)
                            .addComponent(cruiseControlTxtField)
                            .addComponent(accelerationTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fuelEconomyTxtField)
                            .addComponent(fuelTankCapacityTxtField)
                            .addComponent(horsePowerTxtField)
                            .addComponent(serialNumberTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel)
                            .addComponent(colourLabel)
                            .addComponent(transmissionLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transmissionTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modeltxtField)
                            .addComponent(colourTxtField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engineLabel)
                            .addComponent(seatingCapacityLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatingCapacityTxtField)
                            .addComponent(engineTxtField))))
                .addGap(49, 49, 49)
                .addComponent(carImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelLabel)
                            .addComponent(modeltxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transmissionLabel)
                            .addComponent(transmissionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colourLabel)
                            .addComponent(colourTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineLabel)
                            .addComponent(engineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatingCapacityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horsePowerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horsepowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelTankCapacityLabel)
                            .addComponent(fuelTankCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelEcomonyLabel)
                            .addComponent(fuelEconomyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNumberLabel)
                            .addComponent(serialNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cruiseControlLabel)
                            .addComponent(cruiseControlTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxSpeedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brandLabel)
                            .addComponent(BrandTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bootSpaceLabel)
                            .addComponent(bootSpaceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bodyMaterialLabel)
                            .addComponent(bodyMaterialTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accelerationLabel)
                            .addComponent(accelerationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(carImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandTxtField;
    private javax.swing.JLabel accelerationLabel;
    private javax.swing.JTextField accelerationTxtField;
    private javax.swing.JLabel bodyMaterialLabel;
    private javax.swing.JTextField bodyMaterialTxtField;
    private javax.swing.JLabel bootSpaceLabel;
    private javax.swing.JTextField bootSpaceTxtField;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel carImageLabel;
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTxtField;
    private javax.swing.JLabel cruiseControlLabel;
    private javax.swing.JTextField cruiseControlTxtField;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JTextField engineTxtField;
    private javax.swing.JLabel fuelEcomonyLabel;
    private javax.swing.JTextField fuelEconomyTxtField;
    private javax.swing.JLabel fuelTankCapacityLabel;
    private javax.swing.JTextField fuelTankCapacityTxtField;
    private javax.swing.JTextField horsePowerTxtField;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel maxSpeedLabel;
    private javax.swing.JTextField maxSpeedTxtField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modeltxtField;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel seatingCapacityLabel;
    private javax.swing.JTextField seatingCapacityTxtField;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JTextField serialNumberTxtField;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JTextField transmissionTxtField;
    // End of variables declaration//GEN-END:variables
}
