/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shahd
 */
public class CarManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form CarManagePanel
     */
  
    private JPanel rightPanel;
    private CarCatalog carCatalog;
   public CarManagePanel(JPanel rightPanel, CarCatalog carCatalog) {
        initComponents();
        this.rightPanel=rightPanel;
        this.carCatalog=carCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseCar = new javax.swing.JButton();
        createCar = new javax.swing.JButton();
        getFirstCarButton = new javax.swing.JButton();
        multiFilterButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 102, 255));

        browseCar.setText("Browse Catalog");
        browseCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCarActionPerformed(evt);
            }
        });

        createCar.setText("Upload Vehicle Information");
        createCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCarActionPerformed(evt);
            }
        });

        getFirstCarButton.setText("Get First Available Car");
        getFirstCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFirstCarButtonActionPerformed(evt);
            }
        });

        multiFilterButton.setText("Search Manufacturers used by Uber");
        multiFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiFilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getFirstCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browseCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getFirstCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(multiFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCarActionPerformed
        // TODO add your handling code here:
        
        UploadJPanel panel = new UploadJPanel(rightPanel, carCatalog);
        rightPanel.add("UploadPanel",panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_createCarActionPerformed

    private void browseCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCarActionPerformed
        // TODO add your handling code here:
        browseJPanel panel = new browseJPanel(rightPanel, carCatalog);
        rightPanel.add("browsePanel",panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_browseCarActionPerformed

    private void getFirstCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFirstCarButtonActionPerformed
        // TODO add your handling code here:
        //calling get first car method to get the object of first car
        Car car = carCatalog.getFirstCar();
        //Displaying the Car in view Panel
        ViewCarPanel viewCarPanel = new ViewCarPanel(rightPanel, car, carCatalog);
        viewCarPanel.disableUpdateButton();
        rightPanel.add("ViewCarPanel",viewCarPanel);
        CardLayout layout =(CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        
    }//GEN-LAST:event_getFirstCarButtonActionPerformed

    private void multiFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiFilterButtonActionPerformed
        // TODO add your handling code here:
        
      multiFilterJPanel multiJPanel = new multiFilterJPanel(rightPanel, carCatalog);
      rightPanel.add("multiFilterJPanel",multiJPanel);
      CardLayout layout =(CardLayout) rightPanel.getLayout();
      layout.next(rightPanel);
        
    }//GEN-LAST:event_multiFilterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseCar;
    private javax.swing.JButton createCar;
    private javax.swing.JButton getFirstCarButton;
    private javax.swing.JButton multiFilterButton;
    // End of variables declaration//GEN-END:variables
}
