/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shahd
 */
public class ViewCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCarPanel
     */
   
    private JPanel rightPanel;
   private CarCatalog carCatalog;
   private Car car;
    public ViewCarPanel(JPanel rightPanel, Car car, CarCatalog carCatalog) {
       initComponents();
        this.rightPanel=rightPanel;
        this.carCatalog=carCatalog;
        this.car=car;
        
        
       brandNameText.setText(car.getBrand());
       yesCheck.setSelected(car.isAvailable());
      
       manufTextField.setText(String.valueOf(car.getManufactured_year()));
       minimumSeatsTextField.setText(String.valueOf(car.getMin_seats()));
       maxFieldTxtField.setText(String.valueOf(car.getMax_seats()));
       modelNumTxtField.setText(car.getModel_num());
       cityCheckBox.setSelectedItem(car.getAvailble_city());
       carTypeCheckBox.setSelectedItem(car.getCar_Type());
       manufacturetxtField.setText(car.getManufacture());
       serialNumberText.setText(String.valueOf(car.getSerial_num()));
       btnSave.setEnabled(false);
       btnUpdate.setEnabled(true);
       expireCheck.setSelected(car.isMaintenance_certificate());
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityCheckBox = new javax.swing.JComboBox<>();
        carTypeCheckBox = new javax.swing.JComboBox<>();
        manufactureLabel = new javax.swing.JLabel();
        manufacturetxtField = new javax.swing.JTextField();
        serialNumberLabel = new javax.swing.JLabel();
        serialNumberText = new javax.swing.JTextField();
        brandNameText = new javax.swing.JTextField();
        manufLabel = new javax.swing.JLabel();
        manufTextField = new javax.swing.JTextField();
        minimumSeatsLabel = new javax.swing.JLabel();
        yesCheck = new javax.swing.JCheckBox();
        maxSeatsLabel = new javax.swing.JLabel();
        expireCheck = new javax.swing.JCheckBox();
        minimumSeatsTextField = new javax.swing.JTextField();
        maxFieldTxtField = new javax.swing.JTextField();
        modelNumLabel = new javax.swing.JLabel();
        modelNumTxtField = new javax.swing.JTextField();
        availCityLabel = new javax.swing.JLabel();
        uploadLabel = new javax.swing.JLabel();
        availableLabel = new javax.swing.JLabel();
        brandNameLabel = new javax.swing.JLabel();
        carTyoeLabel = new javax.swing.JLabel();
        maintainLabel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        cityCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "NewYork", "Chicago", "Seatlle", "Austin", " ", " ", " " }));
        cityCheckBox.setEnabled(false);

        carTypeCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "SportsCar", " " }));
        carTypeCheckBox.setEnabled(false);

        manufactureLabel.setText("Manufacturer");

        manufacturetxtField.setEnabled(false);

        serialNumberLabel.setText("Serial Number");

        serialNumberText.setEnabled(false);

        brandNameText.setEnabled(false);

        manufLabel.setText("Manufacture Year");

        manufTextField.setEnabled(false);

        minimumSeatsLabel.setText("Mininum Seats");

        yesCheck.setText("Yes");
        yesCheck.setEnabled(false);

        maxSeatsLabel.setText("Maximum Seats");

        expireCheck.setText("Not Expired");
        expireCheck.setEnabled(false);

        minimumSeatsTextField.setEnabled(false);

        maxFieldTxtField.setEnabled(false);

        modelNumLabel.setText("Model Number");

        modelNumTxtField.setEnabled(false);

        availCityLabel.setText("Available City");

        uploadLabel.setText("Car Details are Listed Below");

        availableLabel.setText("Is the Car Available");

        brandNameLabel.setText("Brand_Name of the Car");

        carTyoeLabel.setText("Car_Type");

        maintainLabel.setText("Maintaince Certificate ");

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(uploadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxSeatsLabel)
                                    .addComponent(modelNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availableLabel)
                                    .addComponent(brandNameLabel)
                                    .addComponent(manufLabel)
                                    .addComponent(minimumSeatsLabel)
                                    .addComponent(availCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carTyoeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manufactureLabel)
                                    .addComponent(serialNumberLabel)
                                    .addComponent(maintainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelNumTxtField)
                                    .addComponent(maxFieldTxtField)
                                    .addComponent(minimumSeatsTextField)
                                    .addComponent(cityCheckBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manufTextField)
                                    .addComponent(brandNameText)
                                    .addComponent(carTypeCheckBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manufacturetxtField)
                                    .addComponent(serialNumberText)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yesCheck)
                                            .addComponent(expireCheck))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(436, 436, 436))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uploadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableLabel)
                    .addComponent(yesCheck))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandNameLabel)
                    .addComponent(brandNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manufLabel)
                    .addComponent(manufTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(minimumSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minimumSeatsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxSeatsLabel)
                    .addComponent(maxFieldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelNumLabel)
                    .addComponent(modelNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availCityLabel)
                    .addComponent(cityCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carTyoeLabel)
                    .addComponent(carTypeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintainLabel)
                    .addComponent(expireCheck))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufactureLabel)
                    .addComponent(manufacturetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumberLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnBack))
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
             //validations for required fields
            String name = brandNameText.getText();
            if(name==null || name.equals("")){
            JOptionPane.showMessageDialog(null, "Brand name cannot be empty!");
            return;
            }
           
            String model = modelNumTxtField.getText();
            if(model==null || name.equals("")){
            JOptionPane.showMessageDialog(null, "Model Number cannot be empty!");
            return;
            }
            
            String manuf = manufacturetxtField.getText();
            if(manuf==null || name.equals("")){
            JOptionPane.showMessageDialog(null, "Model Number cannot be empty!");
            return;
            }
        
          
           car.setBrand(brandNameText.getText());
           //you cannot parse null value so enter data for code to run or keep a try catch block
           try{
           car.setManufactured_year(Integer.parseInt(manufTextField.getText()));
           car.setManufacture(manufacturetxtField.getText());
           car.setSerial_num(Integer.parseInt(serialNumberText.getText()));
           car.setMin_seats(Integer.parseInt(minimumSeatsTextField.getText()));
           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null,"Number Field cannot be null","ERROR",JOptionPane.ERROR_MESSAGE);
           }
           car.setMax_seats(Integer.parseInt(maxFieldTxtField.getText()));
           car.setModel_num(modelNumTxtField.getText());
           
           car.setAvailble_city((String)cityCheckBox.getSelectedItem());
           car.setCar_Type((String)carTypeCheckBox.getSelectedItem());
           
           if(yesCheck.isSelected()){
           car.setAvailable(true);
           }
           else {
           car.setAvailable(false);
           }
          
           if(expireCheck.isSelected()){
           car.setMaintenance_certificate(true);
           }
           else{
           car.setMaintenance_certificate(false);
           }
           
        
        
        
         yesCheck.setEnabled(false);
        brandNameText.setEnabled(false);
        manufTextField.setEnabled(false);
        manufacturetxtField.setEnabled(false);
        maxSeatsLabel.setEnabled(false);
        minimumSeatsTextField.setEnabled(false);
        serialNumberText.setEnabled(false);
        modelNumTxtField.setEnabled(false);
        cityCheckBox.setEnabled(false);
        carTypeCheckBox.setEnabled(false);
        expireCheck.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);

        JOptionPane.showMessageDialog(null, "Product updated successfully");
        
        Calendar now = Calendar.getInstance();
        CarCatalog.setLatestUpdate(now.getTime());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        yesCheck.setEnabled(true);
        brandNameText.setEnabled(true);
        manufTextField.setEnabled(true);
        manufacturetxtField.setEnabled(true);
        maxSeatsLabel.setEnabled(true);
        minimumSeatsTextField.setEnabled(true);
        serialNumberText.setEnabled(true);
        modelNumTxtField.setEnabled(true);
        cityCheckBox.setEnabled(true);
        carTypeCheckBox.setEnabled(true);
        expireCheck.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      this.rightPanel.remove(this);
        CardLayout layout = (CardLayout)this.rightPanel.getLayout();

        Component[] comps = this.rightPanel.getComponents();
        for(Component comp :  comps){
            if(comp instanceof browseJPanel){
                browseJPanel browseJpanel = (browseJPanel) comp;
                browseJpanel.populate(carCatalog);
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    
       public void disableUpdateButton (){
                
        btnUpdate.setEnabled(false);
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availCityLabel;
    private javax.swing.JLabel availableLabel;
    private javax.swing.JLabel brandNameLabel;
    private javax.swing.JTextField brandNameText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel carTyoeLabel;
    private javax.swing.JComboBox<String> carTypeCheckBox;
    private javax.swing.JComboBox<String> cityCheckBox;
    private javax.swing.JCheckBox expireCheck;
    private javax.swing.JLabel maintainLabel;
    private javax.swing.JLabel manufLabel;
    private javax.swing.JTextField manufTextField;
    private javax.swing.JLabel manufactureLabel;
    private javax.swing.JTextField manufacturetxtField;
    private javax.swing.JTextField maxFieldTxtField;
    private javax.swing.JLabel maxSeatsLabel;
    private javax.swing.JLabel minimumSeatsLabel;
    private javax.swing.JTextField minimumSeatsTextField;
    private javax.swing.JLabel modelNumLabel;
    private javax.swing.JTextField modelNumTxtField;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JTextField serialNumberText;
    private javax.swing.JLabel uploadLabel;
    private javax.swing.JCheckBox yesCheck;
    // End of variables declaration//GEN-END:variables
}
