/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SportStoreEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.TrekManagerOrganization;
import Business.Organization.TrekPaymentOrganization;
import Business.Role.CustomerRole;
import Business.Role.TrekPaymentManagerRole;
import Business.Trek.Trek;
import Business.Trek.TrekBooking;
import Business.Trek.TrekSlotAndCost;
import Business.UserAccount.UserAccount;
import Business.Validations.Validations;
import Business.WorkQueue.ConfirmPaymentWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dedhi
 */
public class CustomerBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerBookingJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerOrganization customerOrganization;
    private TrekManagerOrganization trekManagerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Trek trek;
    private int customerTotalSeats;
    private String selectedSlot;
    private TrekSlotAndCost trekSlotAndCost;
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    private TrekPaymentOrganization trekPaymentOrganization;
    private Validations validations = new Validations();
    public CustomerBookingJPanel(JPanel userProcessContainer, UserAccount account, CustomerOrganization customerOrganization, Enterprise enterprise, EcoSystem business, int customerTotalSeats, Trek trek, String selectedSlot ) throws ParseException {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.customerOrganization = customerOrganization;
        this.enterprise = enterprise;
        this.business = business;
        this.trek = trek;
        this.customerTotalSeats = customerTotalSeats;
        this.selectedSlot = selectedSlot;
        populateData();
    }
    
    public void populateData() throws ParseException{
        trekLocLabel.setText(trek.getTrekLocation());
        trekDurationLabel.setText(String.valueOf(trek.getTrekDuration()));
        trekLeaderLabel.setText(trek.getTrekLeader());
        trekSlotLabel.setText(selectedSlot);
        totalTrekkersLabel.setText(String.valueOf(customerTotalSeats));
        for(TrekSlotAndCost t: trek.getTrekSlotAndCost()){
            Date trekDate = dateFormat.parse(dateFormat.format(t.getTrekStartDate()));
            if(trekDate.compareTo(dateFormat.parse(selectedSlot)) == 0){
                trekSlotAndCost = t;
                break;
            }
        }
        travelCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTravelCost()));
        accomodationCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekAccomodationCost()));
        mealCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekMealCost()));
        medicalEmergencyLabel.setText(String.valueOf(trekSlotAndCost.getTrekMedicalEmergency()));
        taxLabel.setText(String.valueOf(trekSlotAndCost.getTrekTax()));
        totalCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTotalCost()*customerTotalSeats));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        trekLocLabel = new javax.swing.JLabel();
        trekDurationLabel = new javax.swing.JLabel();
        trekLeaderLabel = new javax.swing.JLabel();
        travelCostLabel = new javax.swing.JLabel();
        accomodationCostLabel = new javax.swing.JLabel();
        mealCostLabel = new javax.swing.JLabel();
        medicalEmergencyLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalTrekkersLabel = new javax.swing.JLabel();
        trekSlotLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ccCVV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        expiryDate1 = new javax.swing.JTextField();
        ccNumber1 = new javax.swing.JTextField();
        ccHolderName1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        confirmBookingButton1 = new javax.swing.JButton();
        expiryDate2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 108, 205));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Trek Location");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duration");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trek Leader");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Trek Cost");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Travel Cost/person in $");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Accomodation Cost/person in $");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Meal Cost/person in $");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Medical Emergency/person in $");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tax (6.5%)");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total Cost");

        trekLocLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekLocLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        trekLocLabel.setOpaque(true);

        trekDurationLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekDurationLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        trekDurationLabel.setOpaque(true);

        trekLeaderLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekLeaderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        trekLeaderLabel.setOpaque(true);

        travelCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        travelCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        travelCostLabel.setOpaque(true);

        accomodationCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        accomodationCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        accomodationCostLabel.setOpaque(true);

        mealCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        mealCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        mealCostLabel.setOpaque(true);

        medicalEmergencyLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicalEmergencyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        medicalEmergencyLabel.setOpaque(true);

        taxLabel.setBackground(new java.awt.Color(255, 255, 255));
        taxLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        taxLabel.setOpaque(true);

        totalCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        totalCostLabel.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trek Slot");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Trekkers");

        totalTrekkersLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalTrekkersLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        totalTrekkersLabel.setOpaque(true);

        trekSlotLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekSlotLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        trekSlotLabel.setOpaque(true);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/backButton.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 108, 205));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credit Card Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        ccCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccCVVActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CVV");

        ccNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccNumber1ActionPerformed(evt);
            }
        });

        ccHolderName1.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Expiry Date");

        jLabel14.setText("/");

        confirmBookingButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/confirmBookingButton.png"))); // NOI18N
        confirmBookingButton1.setContentAreaFilled(false);
        confirmBookingButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmBookingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingButton1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Credit Card Holder Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credit Card Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(confirmBookingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ccHolderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(expiryDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expiryDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(ccCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccHolderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(expiryDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(confirmBookingButton1)
                .addGap(46, 46, 46))
        );

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Booking Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(trekSlotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trekDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trekLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trekLeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalTrekkersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(travelCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accomodationCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mealCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicalEmergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(418, 418, 418))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(trekLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(trekDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(trekLeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(trekSlotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(travelCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(accomodationCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(mealCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(medicalEmergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(totalTrekkersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handlig code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ccCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccCVVActionPerformed

    private void ccNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccNumber1ActionPerformed

    private void confirmBookingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingButton1ActionPerformed
        // TODO add your handling code here:
        String cardHolder = ccHolderName1.getText();
        String cardNumber = ccNumber1.getText();
        String expiryDate = expiryDate1.getText()+"/"+expiryDate2.getText();
        String cvv = ccCVV.getText();

        if(cardHolder == null || cardHolder.isEmpty()){
            JOptionPane.showMessageDialog(null, "Card Holder Name cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.onlyLettersValidation(cardHolder)){
            JOptionPane.showMessageDialog(null, "Card Holder Name can only contain letters","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(cardNumber == null || cardNumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Card Number cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.sixteenDigits(cardNumber)){
            JOptionPane.showMessageDialog(null, "Card Number must be of 16 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(expiryDate1.getText() == null || expiryDate1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Expiry Month cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.twoDigits(expiryDate1.getText())){
            JOptionPane.showMessageDialog(null, "Expiry Month must be of 2 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(expiryDate2.getText() == null || expiryDate2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Expiry Year cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!validations.twoDigits(expiryDate2.getText())){
            JOptionPane.showMessageDialog(null, "Expiry Year must be of 2 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(cvv == null || cvv.isEmpty()){
            JOptionPane.showMessageDialog(null, "CVV cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.threeDigits(cvv)){
            JOptionPane.showMessageDialog(null, "CVV must be of 3 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        ConfirmPaymentWorkRequest request = new ConfirmPaymentWorkRequest();
        request.setSender(account);
        request.setStatus("Payment pending for confirmation");
        request.setCardHolderName(cardHolder);
        request.setCardNumber(cardNumber);
        request.setExpiryDate(expiryDate);
        request.setCvv(cvv);
        TrekBooking trekBooking = new TrekBooking();
        trekBooking.setTrek(trek);
        trekBooking.setCustomer(account);
        trekBooking.setTotalTrekkers(Integer.parseInt(totalTrekkersLabel.getText()));
        trekBooking.setTrekSlotAndCost(trekSlotAndCost);
        trekBooking.setBookingDate(new Date());
        request.setTrekBooking(trekBooking);
        account.getWorkQueue().getWorkRequestList().add(request);
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof TrekPaymentOrganization){
                trekPaymentOrganization = (TrekPaymentOrganization) org;
                break;
            }
        }
        if(trekPaymentOrganization != null){
            trekPaymentOrganization.getWorkQueue().getWorkRequestList().add(request);
        }
        
        //code to get sports enterprise
         Enterprise.EnterpriseType type = enterprise.getEnterpriseType();
        Network network = null;
        SportStoreEnterprise sportStoreEnterprise = null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e == enterprise){
                    network = n;
                            break;
        }
            }
        }
        if(network != null){
            for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SportStoreEnterprise){
                    sportStoreEnterprise = (SportStoreEnterprise) e;
                    break;
                }
            }
        }
        System.out.println("sportsstoreenterprise: "+sportStoreEnterprise);
        //
        int reply = JOptionPane.showConfirmDialog(null, "Payment sent for confirmation. Would you like to buy the best gears for your trek?","Payment processing!",JOptionPane.YES_NO_OPTION);
        if(reply == 0){
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("CustomerSportsStoreWorkAreaJPanel",new CustomerSportsStoreWorkAreaJPanel(userProcessContainer, account, customerOrganization, sportStoreEnterprise, business));
            layout.next(userProcessContainer);
        } else{
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            try {
                userProcessContainer.add("CutomerTrekCompanyWorkAreaJPanel",new CutomerTrekCompanyWorkAreaJPanel(userProcessContainer, account, customerOrganization, enterprise, business));
            } catch (ParseException ex) {
                Logger.getLogger(CustomerBookingJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            layout.next(userProcessContainer);
        }


    }//GEN-LAST:event_confirmBookingButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accomodationCostLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField ccCVV;
    private javax.swing.JTextField ccHolderName1;
    private javax.swing.JTextField ccNumber1;
    private javax.swing.JButton confirmBookingButton1;
    private javax.swing.JTextField expiryDate1;
    private javax.swing.JTextField expiryDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mealCostLabel;
    private javax.swing.JLabel medicalEmergencyLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalTrekkersLabel;
    private javax.swing.JLabel travelCostLabel;
    private javax.swing.JLabel trekDurationLabel;
    private javax.swing.JLabel trekLeaderLabel;
    private javax.swing.JLabel trekLocLabel;
    private javax.swing.JLabel trekSlotLabel;
    // End of variables declaration//GEN-END:variables
}
