/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SportStoreEnterprise;
import Business.Enterprise.TrekCompanyEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.TrekManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddTrekCostWorkRequest;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import UserInterface.TrekFinanceManagerRole.CostPlanningJPanel;

/**
 *
 * @author dedhi
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerOrganization customerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CustomerOrganization customerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.customerOrganization = customerOrganization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookTrekButton = new javax.swing.JButton();
        storeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 108, 205));

        bookTrekButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/bookATrek.png"))); // NOI18N
        bookTrekButton.setContentAreaFilled(false);
        bookTrekButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookTrekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTrekButtonActionPerformed(evt);
            }
        });

        storeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/sportsEquipment.png"))); // NOI18N
        storeButton.setContentAreaFilled(false);
        storeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(bookTrekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(bookTrekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookTrekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTrekButtonActionPerformed
        // TODO add your handling code here:
        Enterprise.EnterpriseType type = enterprise.getEnterpriseType();
        Network network = null;
        TrekCompanyEnterprise trekCompanyEnterprise = null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e == enterprise){
                    network = n;
                            break;
        }
            }
        }
        if(network != null){
            for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof TrekCompanyEnterprise){
                    trekCompanyEnterprise = (TrekCompanyEnterprise) e;
                    break;
                }
            }
        }
        if(trekCompanyEnterprise!=null){
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        try {
            userProcessContainer.add("CustomerTrekCompanyWorkAreaJPanel",new CutomerTrekCompanyWorkAreaJPanel(userProcessContainer, account, customerOrganization, trekCompanyEnterprise, business));
        } catch (ParseException ex) {
            Logger.getLogger(CustomerWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_bookTrekButtonActionPerformed

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        // TODO add your handling code here:
        Enterprise.EnterpriseType type = enterprise.getEnterpriseType();
        Network network = null;
        SportStoreEnterprise sportStoreEnterprise = null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e == enterprise){
                    network = n;
                            break;
        }
            }
        }
        if(network != null){
            for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SportStoreEnterprise){
                    sportStoreEnterprise = (SportStoreEnterprise) e;
                    break;
                }
            }
        }
        if(sportStoreEnterprise != null){
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add("CustomerSportsStoreWorkAreaJPanel",new UserInterface.CustomerRole.CustomerSportsStoreWorkAreaJPanel(userProcessContainer, account, customerOrganization, sportStoreEnterprise, business));
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_storeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTrekButton;
    private javax.swing.JButton storeButton;
    // End of variables declaration//GEN-END:variables
}
