/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.TrekManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.Validations.Validations;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dedhi
 */
public class CustomerSignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSignUpJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Validations validations = new Validations();
    public CustomerSignUpJPanel(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateNetworkComboBox();
    }
    
    public void populateNetworkComboBox(){
        networkComboBox.removeAllItems();
        for(Network network: business.getNetworkList()){
            networkComboBox.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTxtField = new javax.swing.JTextField();
        passwordTxtField = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 108, 205));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        userNameTxtField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        passwordTxtField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        signUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/signUpButton.png"))); // NOI18N
        signUpButton.setContentAreaFilled(false);
        signUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Network");

        networkComboBox.setBackground(new java.awt.Color(153, 255, 255));
        networkComboBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Sign Up");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(signUpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(signUpButton)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkComboBox.getSelectedItem();
      
        if(userNameTxtField.getText() == null || userNameTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username cannt be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validations.usernamePatternCorrect(userNameTxtField.getText())){
            JOptionPane.showMessageDialog(null, "Your username should be a correct Mail ID","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (passwordTxtField.getText() == null || passwordTxtField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Password cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
            for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                if(org instanceof CustomerOrganization){
                    CustomerOrganization customerOrganization = (CustomerOrganization) org;
                    for(UserAccount account: customerOrganization.getUserAccountDirectory().getUserAccountList()){
                        System.out.println("username entered: "+userNameTxtField.getText());
                        System.out.println("user present: "+account.getUsername());
                        if(account.getUsername().equals(userNameTxtField.getText())){
                        JOptionPane.showMessageDialog(null, "Username already exist","Warning",JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                        
                        if(!validations.passwordPatternCorrect(passwordTxtField.getText())){
                        JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and a combination of number, upper case, lower case and special characters $, *, # or &!","Warning",JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                    
                    Employee employee = org.getEmployeeDirectory().createEmployee(userNameTxtField.getText());
                    org.getUserAccountDirectory().createUserAccount(userNameTxtField.getText(), passwordTxtField.getText(), employee , org.getSupportedRole().get(0));
                    break;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "User account created successfully");
        userNameTxtField.setText("");
        passwordTxtField.setText("");
        userProcessContainer.remove(this);
    }//GEN-LAST:event_signUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userNameTxtField;
    // End of variables declaration//GEN-END:variables
}
