/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.SportsStoreManagerOrganization;
import Business.Organization.SportsStorePaymentOrganization;
import Business.Organization.TrekPaymentOrganization;
import Business.Products.CustomerItems;
import Business.Products.CustomerOrders;
import Business.Products.MyCartDirectory;
import Business.UserAccount.UserAccount;
import Business.Validations.Validations;
import Business.WorkQueue.ConfirmPaymentWorkRequest;
import Business.WorkQueue.SportsStoreConfirmPaymentRequest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shahd
 */
public class SportsStoreBookingDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SportsStoreBookingDetails
     */
    private MyCartDirectory mycartList;
    private ArrayList<CustomerItems> custList;
     private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerOrganization customerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private SportsStoreManagerOrganization sportsStoreManagerOrganization;
    private Validations validations = new Validations();
     private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    private SportsStorePaymentOrganization paymentOrganization;

    public SportsStoreBookingDetailsJPanel(JPanel userProcessContainer, UserAccount account, CustomerOrganization customerOrganization, Enterprise enterprise, EcoSystem business,ArrayList<CustomerItems> custList) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.customerOrganization = customerOrganization;
        this.enterprise = enterprise;
        this.business = business;
        this.custList=custList;
        System.out.println(custList);
        
        displayBookingDetails();
        //ccHolderName.setBorder(BorderFactory.createTitledBorder("Credit Card Holder Name"));
        //ccNumber.setBorder(BorderFactory.createTitledBorder("Credit Card Number"));
    }

    
    
    public void displayBookingDetails(){
    
        int totalP = 0;
        int totalqty=0;
        double totalCostCount =0;
        for(CustomerItems item : custList){
            totalP++;
            totalqty=totalqty+item.getQuantity();
            totalCostCount=totalCostCount+(item.getProduct().getCostPrice()*item.getQuantity());
        
        }
        
        totalProds.setText(String.valueOf(totalP));
        totalQty.setText(String.valueOf(totalqty));
        double totalCostplusTaxes = 0;
        
        totalCostplusTaxes = totalCostCount+((totalCostCount*6.25)/100);
        
        totalCost.setText(String.valueOf(totalCostplusTaxes));
        
        
    
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalProducts = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalProds = new javax.swing.JLabel();
        totalQty = new javax.swing.JLabel();
        totalCost = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ccCVV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        expiryDate1 = new javax.swing.JTextField();
        ccNumber1 = new javax.swing.JTextField();
        ccHolderName1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        confirmBookingButton1 = new javax.swing.JButton();
        expiryDate2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 108, 205));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Details");

        totalProducts.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalProducts.setForeground(new java.awt.Color(255, 255, 255));
        totalProducts.setText("Total Number of Products");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Quantity");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Cost + taxes");

        totalProds.setBackground(new java.awt.Color(255, 255, 255));
        totalProds.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalProds.setOpaque(true);

        totalQty.setBackground(new java.awt.Color(255, 255, 255));
        totalQty.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalQty.setOpaque(true);

        totalCost.setBackground(new java.awt.Color(255, 255, 255));
        totalCost.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalCost.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(33, 108, 205));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credit Card Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        ccCVV.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ccCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccCVVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CVV");

        expiryDate1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        ccNumber1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ccNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccNumber1ActionPerformed(evt);
            }
        });

        ccHolderName1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ccHolderName1.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Expiry Date");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel13.setText("/");

        confirmBookingButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/confirmBookingButton.png"))); // NOI18N
        confirmBookingButton1.setContentAreaFilled(false);
        confirmBookingButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmBookingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingButton1ActionPerformed(evt);
            }
        });

        expiryDate2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Credit Card Holder Name");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credit Card Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccHolderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(expiryDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expiryDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(ccCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(confirmBookingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccHolderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(expiryDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(confirmBookingButton1)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalProds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(459, 459, 459))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalProds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totalQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ccNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccNumber1ActionPerformed

    private void confirmBookingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingButton1ActionPerformed
        // TODO add your handling code here:
        
        String cardHolder = ccHolderName1.getText();
        String cardNumber = ccNumber1.getText();
        String expiryDate = expiryDate1.getText()+expiryDate2.getText();
        String cvv = ccCVV.getText();

        if(cardHolder == null || cardHolder.isEmpty()){
            JOptionPane.showMessageDialog(null, "Card Holder Name cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.onlyLettersValidation(cardHolder)){
            JOptionPane.showMessageDialog(null, "Card Holder Name can only contain letters","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(cardNumber == null || cardNumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Card Number cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.sixteenDigits(cardNumber)){
            JOptionPane.showMessageDialog(null, "Card Number must be of 16 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(expiryDate1.getText() == null || expiryDate1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Expiry Month cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.twoDigits(expiryDate1.getText())){
            JOptionPane.showMessageDialog(null, "Expiry Month must be of 2 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(expiryDate2.getText() == null || expiryDate2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Expiry Year cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!validations.twoDigits(expiryDate2.getText())){
            JOptionPane.showMessageDialog(null, "Expiry Year must be of 2 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(cvv == null || cvv.isEmpty()){
            JOptionPane.showMessageDialog(null, "CVV cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!validations.threeDigits(cvv)){
            JOptionPane.showMessageDialog(null, "CVV must be of 3 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        for(CustomerItems item : custList){
            SportsStoreConfirmPaymentRequest request = new SportsStoreConfirmPaymentRequest();
            request.setSender(account);
            request.setStatus("Payment pending for confirmation");
            request.setCardHolderName(cardHolder);
            request.setCardNumber(cardNumber);
            request.setExpiryDate(expiryDate);
            request.setCvv(cvv);
            CustomerOrders ord = new CustomerOrders();
            ord.setProduct(item.getProduct());
            ord.setCustAccount(item.getCustAccount());
            ord.setQuantity(item.getQuantity());
            ord.setOrderDate(new Date());
            request.setCustOrder(ord);
            account.getWorkQueue().getWorkRequestList().add(request);
            for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                if(org instanceof SportsStorePaymentOrganization){
                    paymentOrganization = (SportsStorePaymentOrganization) org;
                    break;
                }
            }
            if(paymentOrganization != null){
                paymentOrganization.getWorkQueue().getWorkRequestList().add(request);
            }
        }

        JOptionPane.showMessageDialog(null, "Payment sent for confirmation");
        ccHolderName1.setText("");
        ccNumber1.setText("");
        expiryDate1.setText("");
        expiryDate2.setText("");
        ccCVV.setText("");
        JOptionPane.showMessageDialog(null,"Please login again","Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_confirmBookingButton1ActionPerformed

    private void ccCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccCVVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccCVV;
    private javax.swing.JTextField ccHolderName1;
    private javax.swing.JTextField ccNumber1;
    private javax.swing.JButton confirmBookingButton1;
    private javax.swing.JTextField expiryDate1;
    private javax.swing.JTextField expiryDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel totalCost;
    private javax.swing.JLabel totalProds;
    private javax.swing.JLabel totalProducts;
    private javax.swing.JLabel totalQty;
    // End of variables declaration//GEN-END:variables
}
