/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.TrekManagerOrganization;
import Business.Trek.Trek;
import Business.Trek.TrekSlotAndCost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dedhi
 */
public class TrekDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrekDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerOrganization customerOrganization;
    private TrekManagerOrganization trekManagerOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Trek trek;
    private ArrayList<String> trekImagePath = new ArrayList<String>();
    private int count = 0;
    private TrekSlotAndCost trekSlotAndCost = null;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm"); 
    public TrekDetailsJPanel(JPanel userProcessContainer, UserAccount account, CustomerOrganization customerOrganization, Enterprise enterprise, EcoSystem business, Trek trek) throws ParseException {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.customerOrganization = customerOrganization;
        this.enterprise = enterprise;
        this.business = business;
        this.trek = trek;
        initComponents();
        populateTrekSlotComboBox();
        trekData();
        displayImage(trekImagePath.get(0));
        
    }
    
    public void trekData(){
        trekNameLabel.setText(trek.getTrekName());
        trekImagePath = trek.getTrekImages();
        trekLocLabel.setText(trek.getTrekLocation());
        trekDescLabel.setText(trek.getTrekDescription());
        trekDifficultyLevelLabel.setText(trek.getTrekDifficultyLevel());
        trekBasicReqLabel.setText(trek.getTrekBasicRequirement());
        trekDurationLabel.setText(String.valueOf(trek.getTrekDuration()));
        trekItineraryLabel.setText(trek.getTrekItinerary());
        trekWeatherLabel.setText(trek.getTrekWeather());
        trekPickUpPointLabel.setText(trek.getTrekPickUpPoint());
        trekBaseCampLabel.setText(trek.getTrekBaseCamp());
        trekMaxAltitudeLabel.setText(String.valueOf(trek.getTrekMaxAltitude()));
        trekMinAgeLabel.setText(String.valueOf(trek.getTrekMinAge()));
        trekBestTimeToTrekLabel.setText(trek.getTrekBestTimeToVisit());
        trekFitnessRequiredLabel.setText(trek.getTrekFitnessRequired());
        trekLeaderLabel.setText(trek.getTrekLeader());
        availableSeatsLabel.setText(String.valueOf(trekSlotAndCost.getAvailableSeats()));
        travelCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTravelCost()));
        accomodationCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekAccomodationCost()));
        mealCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekMealCost()));
        medicalEmergencyLabel.setText(String.valueOf(trekSlotAndCost.getTrekMedicalEmergency()));
        taxLabel.setText(String.valueOf(trekSlotAndCost.getTrekTax()));
        totalCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTotalCost()));
   }
    
    public void displayImage(String trekImagePath){
        trekImageLabel.setIcon(new ImageIcon(new ImageIcon(trekImagePath).getImage().getScaledInstance(483, 300, Image.SCALE_SMOOTH)));	
    }
    
    public void populateTrekSlotComboBox() throws ParseException{
        trekSlots.removeAllItems();
        for(TrekSlotAndCost trekSlotAndCost: trek.getTrekSlotAndCost()){
            System.out.println("slot: "+trekSlotAndCost.getTrekStartDate());
            //String strDate = dateFormat.format(trekSlotAndCost.getTrekStartDate());
            Date currentDate = dateFormat.parse(dateFormat.format(new Date()));
            Date startDate = dateFormat.parse(dateFormat.format(trekSlotAndCost.getTrekStartDate()));
            if(startDate.compareTo(currentDate) >= 0){
                trekSlots.addItem(trekSlotAndCost);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        trekNameLabel = new javax.swing.JLabel();
        trekImageLabel = new javax.swing.JLabel();
        imagePreviousButton = new javax.swing.JButton();
        imageNextButton = new javax.swing.JButton();
        bookNowButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        trekLocLabel = new javax.swing.JLabel();
        trekDescLabel = new javax.swing.JLabel();
        trekDifficultyLevelLabel = new javax.swing.JLabel();
        trekDurationLabel = new javax.swing.JLabel();
        trekBasicReqLabel = new javax.swing.JLabel();
        trekWeatherLabel = new javax.swing.JLabel();
        trekItineraryLabel = new javax.swing.JLabel();
        trekPickUpPointLabel = new javax.swing.JLabel();
        trekMaxAltitudeLabel = new javax.swing.JLabel();
        trekBaseCampLabel = new javax.swing.JLabel();
        trekMinAgeLabel = new javax.swing.JLabel();
        trekBestTimeToTrekLabel = new javax.swing.JLabel();
        trekFitnessRequiredLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        trekLeaderLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        travelCostLabel = new javax.swing.JLabel();
        accomodationCostLabel = new javax.swing.JLabel();
        mealCostLabel = new javax.swing.JLabel();
        medicalEmergencyLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        slotLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        availableSeatsLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        customerTotalSeats = new javax.swing.JTextField();
        trekSlots = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 108, 205));

        jScrollPane1.setBackground(new java.awt.Color(33, 108, 205));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel1.setBackground(new java.awt.Color(33, 108, 205));

        trekNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        trekNameLabel.setForeground(new java.awt.Color(255, 255, 255));

        imagePreviousButton.setText("<<");
        imagePreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePreviousButtonActionPerformed(evt);
            }
        });

        imageNextButton.setText(">>");
        imageNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageNextButtonActionPerformed(evt);
            }
        });

        bookNowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/bookNowButton.png"))); // NOI18N
        bookNowButton.setContentAreaFilled(false);
        bookNowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNowButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Trek Location");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trek Description");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Difficulty Level");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Basic Requirements");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duration");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Trek Itinerary");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Weather");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pick Up Point");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Base Camp");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Maximum Altitude");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Minimum Age");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Best Time to trek");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fitness Required");

        trekLocLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekLocLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekLocLabel.setOpaque(true);

        trekDescLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekDescLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekDescLabel.setOpaque(true);

        trekDifficultyLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekDifficultyLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekDifficultyLevelLabel.setOpaque(true);

        trekDurationLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekDurationLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekDurationLabel.setOpaque(true);

        trekBasicReqLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekBasicReqLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekBasicReqLabel.setOpaque(true);

        trekWeatherLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekWeatherLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekWeatherLabel.setOpaque(true);

        trekItineraryLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekItineraryLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekItineraryLabel.setOpaque(true);

        trekPickUpPointLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekPickUpPointLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekPickUpPointLabel.setOpaque(true);

        trekMaxAltitudeLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekMaxAltitudeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekMaxAltitudeLabel.setOpaque(true);

        trekBaseCampLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekBaseCampLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekBaseCampLabel.setOpaque(true);

        trekMinAgeLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekMinAgeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekMinAgeLabel.setOpaque(true);

        trekBestTimeToTrekLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekBestTimeToTrekLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekBestTimeToTrekLabel.setOpaque(true);

        trekFitnessRequiredLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekFitnessRequiredLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekFitnessRequiredLabel.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trek Leader");

        trekLeaderLabel.setBackground(new java.awt.Color(255, 255, 255));
        trekLeaderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trekLeaderLabel.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Trek Cost");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Travel Cost/person in $");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Accomodation Cost/person in $");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Meal Cost/person in $");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Medical Emergency/person in $");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tax (6.5%)");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total Cost/person in $");

        travelCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        travelCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        travelCostLabel.setOpaque(true);

        accomodationCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        accomodationCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        accomodationCostLabel.setOpaque(true);

        mealCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        mealCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mealCostLabel.setOpaque(true);

        medicalEmergencyLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicalEmergencyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        medicalEmergencyLabel.setOpaque(true);

        taxLabel.setBackground(new java.awt.Color(255, 255, 255));
        taxLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        taxLabel.setOpaque(true);

        totalCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalCostLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalCostLabel.setOpaque(true);

        slotLabel.setBackground(new java.awt.Color(255, 255, 255));
        slotLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        slotLabel.setForeground(new java.awt.Color(255, 255, 255));
        slotLabel.setText("Select a Slot");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Available Seats");

        availableSeatsLabel.setBackground(new java.awt.Color(255, 255, 255));
        availableSeatsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        availableSeatsLabel.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Enter Total no. of Trekkers");

        customerTotalSeats.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        trekSlots.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        trekSlots.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Easy-Moderate", "Moderate", "Moderate-Difficult", "Difficult" }));
        trekSlots.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                trekSlotsItemStateChanged(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/backButton.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(trekLocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekDifficultyLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekBasicReqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekItineraryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekMaxAltitudeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekPickUpPointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(trekBaseCampLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekWeatherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekMinAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekBestTimeToTrekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekFitnessRequiredLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekLeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(trekSlots, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(backButton)
                                            .addComponent(jLabel23))
                                        .addGap(27, 27, 27)
                                        .addComponent(customerTotalSeats)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(availableSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(travelCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(accomodationCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mealCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(medicalEmergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(bookNowButton))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(528, 528, 528)
                                .addComponent(imagePreviousButton)
                                .addGap(122, 122, 122)
                                .addComponent(imageNextButton))
                            .addComponent(slotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(trekImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(trekNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(trekNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(trekImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageNextButton)
                    .addComponent(imagePreviousButton))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(availableSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(travelCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accomodationCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mealCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(medicalEmergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(trekLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trekDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(trekDifficultyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(trekBasicReqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(trekDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(trekItineraryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(trekWeatherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trekPickUpPointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(trekBaseCampLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trekMaxAltitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(trekMinAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(trekBestTimeToTrekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(trekFitnessRequiredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(trekLeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(slotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trekSlots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(customerTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookNowButton)
                        .addGap(115, 115, 115))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void trekSlotsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_trekSlotsItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            System.out.println("inside state change");
            trekSlotAndCost = (TrekSlotAndCost) evt.getItem();
            availableSeatsLabel.setText(String.valueOf(trekSlotAndCost.getAvailableSeats()));
            travelCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTravelCost()));
            accomodationCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekAccomodationCost()));
            mealCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekMealCost()));
            medicalEmergencyLabel.setText(String.valueOf(trekSlotAndCost.getTrekMedicalEmergency()));
            taxLabel.setText(String.valueOf(trekSlotAndCost.getTrekTax()));
            totalCostLabel.setText(String.valueOf(trekSlotAndCost.getTrekTotalCost()));

            // Item was just selected
        }
    }//GEN-LAST:event_trekSlotsItemStateChanged

    private void bookNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNowButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        if(trekSlots.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please select a slot","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            if(customerTotalSeats.getText() == null || customerTotalSeats.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter Total number of Trekkers","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            int totalTrekkers = Integer.parseInt(customerTotalSeats.getText());
            Date bookedSlot;
            bookedSlot = dateFormat.parse(trekSlots.getSelectedItem().toString());
            for(TrekSlotAndCost trekSlotAndCost: trek.getTrekSlotAndCost()){
                Date trekSlot;
                trekSlot = dateFormat.parse(dateFormat.format(trekSlotAndCost.getTrekStartDate()));
                if(bookedSlot.compareTo(trekSlot) == 0){
                    int availableSeats = trekSlotAndCost.getAvailableSeats();
                    if(totalTrekkers > availableSeats){
                        JOptionPane.showMessageDialog(null, "Less seats available", "Warning", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    System.out.println("available seats: "+availableSeats);
                    System.out.println("total trekkers: "+totalTrekkers);
                    trekSlotAndCost.setAvailableSeats(availableSeats-totalTrekkers);
                }
            }

            userProcessContainer.add("CustomerBookingJPanel",new CustomerBookingJPanel(userProcessContainer, account, customerOrganization, enterprise, business,totalTrekkers , trek, trekSlots.getSelectedItem().toString()));
        } catch (ParseException ex) {
            Logger.getLogger(TrekDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a valid number","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bookNowButtonActionPerformed

    private void imageNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageNextButtonActionPerformed
        // TODO add your handling code here:
        if(count==trekImagePath.size()-1){
            count=-1;
        }
        displayImage(trekImagePath.get(count+1));
        count++;
    }//GEN-LAST:event_imageNextButtonActionPerformed

    private void imagePreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePreviousButtonActionPerformed
        // TODO add your handling code here:
        if(count==0){
            count=trekImagePath.size();
        }
        displayImage(trekImagePath.get(count-1));
        count--;
    }//GEN-LAST:event_imagePreviousButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accomodationCostLabel;
    private javax.swing.JLabel availableSeatsLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookNowButton;
    private javax.swing.JTextField customerTotalSeats;
    private javax.swing.JButton imageNextButton;
    private javax.swing.JButton imagePreviousButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mealCostLabel;
    private javax.swing.JLabel medicalEmergencyLabel;
    private javax.swing.JLabel slotLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel travelCostLabel;
    private javax.swing.JLabel trekBaseCampLabel;
    private javax.swing.JLabel trekBasicReqLabel;
    private javax.swing.JLabel trekBestTimeToTrekLabel;
    private javax.swing.JLabel trekDescLabel;
    private javax.swing.JLabel trekDifficultyLevelLabel;
    private javax.swing.JLabel trekDurationLabel;
    private javax.swing.JLabel trekFitnessRequiredLabel;
    private javax.swing.JLabel trekImageLabel;
    private javax.swing.JLabel trekItineraryLabel;
    private javax.swing.JLabel trekLeaderLabel;
    private javax.swing.JLabel trekLocLabel;
    private javax.swing.JLabel trekMaxAltitudeLabel;
    private javax.swing.JLabel trekMinAgeLabel;
    private javax.swing.JLabel trekNameLabel;
    private javax.swing.JLabel trekPickUpPointLabel;
    private javax.swing.JComboBox trekSlots;
    private javax.swing.JLabel trekWeatherLabel;
    // End of variables declaration//GEN-END:variables
}
