/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.ConfigurationFile;
import UserInterface.LoginScreen;
import UserInterface.ManageFlight.ManageAirlinerFlightScheduleJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author shahd
 */
public class CreateAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerJPanel
     */
    private JPanel jPanelRight;
    private AirlinerDirectory airlinerDirectory;
    private JPanel jPanelLeft;
    public CreateAirlinerJPanel(JPanel jPanelRight, JPanel jPanelLeft, AirlinerDirectory airlinerDirectory) {
        this.jPanelRight = jPanelRight;
        this.jPanelLeft = jPanelLeft;
        this.airlinerDirectory = airlinerDirectory;
        initComponents();
    }
    
    private boolean onlyLettersValidation(String input){
        Pattern p = Pattern.compile("^[a-zA-Z]+$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    
    private boolean atleastOneLetterValidation(String input){
        Pattern p = Pattern.compile("^([^A-Za-z]+)$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    
    private boolean phoneNumValidation(String input){
        Pattern p = Pattern.compile("^(\\d{10})$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    
    private boolean yearValidation(String input){
        Pattern p = Pattern.compile("^(\\d{4})$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCreateAirliner = new javax.swing.JButton();
        txtAirlinerName = new javax.swing.JTextField();
        txtAirlinerAddress = new javax.swing.JTextField();
        txtAirlinerContactNo = new javax.swing.JTextField();
        txtTotalFlights = new javax.swing.JTextField();
        txtCountryOfOrigin = new javax.swing.JTextField();
        txtYearOfEstablishment = new javax.swing.JTextField();
        txtAirlinerRating = new javax.swing.JTextField();
        jPanelCheckBox = new javax.swing.JPanel();
        cbAirBus1 = new javax.swing.JCheckBox();
        cbAirBus2 = new javax.swing.JCheckBox();
        cbAirBus3 = new javax.swing.JCheckBox();
        cbBoeing1 = new javax.swing.JCheckBox();
        cbBoeing2 = new javax.swing.JCheckBox();
        cbBoeing3 = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Airliner");

        jLabel2.setText("Airliner Name");

        jLabel3.setText("Address");

        jLabel4.setText("Contact No.");

        jLabel5.setText("Total No. of Flights per Day");

        jLabel6.setText("Country of Origin");

        jLabel7.setText("Year of Establishment");

        jLabel8.setText("Aircraft available in the fleet");

        jLabel9.setText("Airliner Rating");

        btnCreateAirliner.setText("CREATE");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        cbAirBus1.setText("Airbus A380");

        cbAirBus2.setText("Airbus A330");

        cbAirBus3.setText("Airbus A340");

        cbBoeing1.setText("Boeing 777");

        cbBoeing2.setText("Boeing 767");
        cbBoeing2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoeing2ActionPerformed(evt);
            }
        });

        cbBoeing3.setText("Boeing 757");

        javax.swing.GroupLayout jPanelCheckBoxLayout = new javax.swing.GroupLayout(jPanelCheckBox);
        jPanelCheckBox.setLayout(jPanelCheckBoxLayout);
        jPanelCheckBoxLayout.setHorizontalGroup(
            jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                        .addComponent(cbAirBus1)
                        .addGap(18, 18, 18)
                        .addComponent(cbAirBus2)
                        .addGap(18, 18, 18)
                        .addComponent(cbAirBus3))
                    .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                        .addComponent(cbBoeing1)
                        .addGap(26, 26, 26)
                        .addComponent(cbBoeing2)
                        .addGap(26, 26, 26)
                        .addComponent(cbBoeing3)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelCheckBoxLayout.setVerticalGroup(
            jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAirBus1)
                    .addComponent(cbAirBus2)
                    .addComponent(cbAirBus3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBoeing1)
                    .addComponent(cbBoeing2)
                    .addComponent(cbBoeing3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setText("admin");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtYearOfEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCountryOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAirlinerRating, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAirlinerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(txtAirlinerAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirlinerContactNo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAirlinerAddress)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAirlinerContactNo)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCountryOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYearOfEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirlinerRating, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoeing2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoeing2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBoeing2ActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        String airlinerName ;
        String airlinerAddress;
        double airlinerContactNumber;
        int totalFlightsPerDay;
        float airlinerRating;
        String countryOfOrigin;
        int yearOfEstablishment;
        ArrayList<String> airlinerAircraftName = new ArrayList<String>();
        
        //Airliner Name
         airlinerName = txtAirlinerName.getText();
            if(airlinerName == null || airlinerName.isEmpty()){
                JOptionPane.showMessageDialog(null, "Airliner Name cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!onlyLettersValidation(airlinerName)){
                JOptionPane.showMessageDialog(null, "Airliner Name can only contain letters","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            for(Airliner a : airlinerDirectory.getAirlinerDirectory()){
                if(a.getAirlinerName().equalsIgnoreCase(airlinerName)){
                    JOptionPane.showMessageDialog(null, "Airliner already exist","Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        
        //Airliner Address
            airlinerAddress = txtAirlinerAddress.getText();
            if(airlinerAddress == null || airlinerAddress.isEmpty()){
                JOptionPane.showMessageDialog(null, "Airliner Address cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(atleastOneLetterValidation(airlinerAddress)){
                JOptionPane.showMessageDialog(null, "Please enter valid Address","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //AirlinerContactNo.
            try{
                if(txtAirlinerContactNo.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Contact Number cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(!phoneNumValidation(txtAirlinerContactNo.getText())){
                    JOptionPane.showMessageDialog(null, "Invalid Contact No., Contact No. can contain only 10 digits","Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                airlinerContactNumber = Double.parseDouble(txtAirlinerContactNo.getText());
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid Contact No.","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //TotalFlightsPerDay
            if(txtTotalFlights.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Total number of flights cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
                totalFlightsPerDay = Integer.parseInt(txtTotalFlights.getText());
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid number for Total Flights per Day","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //CountryOfOrigin
            countryOfOrigin = txtCountryOfOrigin.getText();
            if(countryOfOrigin == null || countryOfOrigin.isEmpty()){
                JOptionPane.showMessageDialog(null, "Country of Origin cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!onlyLettersValidation(countryOfOrigin)){
                JOptionPane.showMessageDialog(null, "Country name can only have letters","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //YearOfEstablishment
            if(txtYearOfEstablishment.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Year of Establishment cannot be empty","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        try {
//            DateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            dateOfEstablishment = sdf.parse(txtDateOfEstablishment.getText());
              if(!yearValidation(txtYearOfEstablishment.getText())){
                  JOptionPane.showMessageDialog(null, "Year of Establishment should be of format 'yyyy'","Warning", JOptionPane.WARNING_MESSAGE);
                  return;
              }
              yearOfEstablishment = Integer.parseInt(txtYearOfEstablishment.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Plesae enter valid Year of Establishment","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Aircrafts
        boolean flag = false;
        for (Component c : jPanelCheckBox.getComponents()) {
            if(c instanceof JCheckBox){
              JCheckBox cb = (JCheckBox)c;
              if (cb.isSelected()){
                  airlinerAircraftName.add(cb.getText());
                  flag = true;
              }  
            }
        }
        if(flag == false){
            JOptionPane.showMessageDialog(null, "Please select atleast one Aircraft","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Rating
        try{
                airlinerRating = Float.parseFloat(txtAirlinerRating.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid number for Rating","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        Airliner airliner = airlinerDirectory.add();
        airliner.setAirlinerName(airlinerName);
        airliner.setAirlinerAddress(airlinerAddress);
        airliner.setAirlinerContactNumber(airlinerContactNumber);
        airliner.setTotalFlightsPerDay(totalFlightsPerDay);
        airliner.setCountryOfOrigin(countryOfOrigin);
        airliner.setYearOfEstablishment(yearOfEstablishment);
        airliner.setAirlinerRating(airlinerRating);
        airliner.setAirlinerAircraftName(airlinerAircraftName);
        JOptionPane.showMessageDialog(null, "Airliner created successfully","Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtAirlinerName.setText("");
        txtAirlinerAddress.setText("");
        txtAirlinerContactNo.setText("");
        txtAirlinerRating.setText("");
        txtCountryOfOrigin.setText("");
        txtYearOfEstablishment.setText("");
        txtTotalFlights.setText("");
        //txtAirlinerName.setText("");
        for (Component c : jPanelCheckBox.getComponents()) {
            if(c instanceof JCheckBox){
              JCheckBox cb = (JCheckBox)c;
              cb.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanelRight.remove(this);

        for(Component comp : jPanelRight.getComponents()){
            if(comp instanceof ManageAirlinerJPanel){
                ManageAirlinerJPanel manageAirlinerJPanel = (ManageAirlinerJPanel) comp;
                manageAirlinerJPanel.populateTable();
            }
        }

        CardLayout layout = (CardLayout)this.jPanelRight.getLayout();
        layout.previous(jPanelRight);
        System.out.println("Create Back: "+jPanelRight.getComponent(jPanelRight.getComponentCount()-1));

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        for(Component comp : jPanelRight.getComponents()){
            if(comp instanceof LoginScreen){

            } else{
                jPanelRight.remove(comp);
            }
            CardLayout layout = (CardLayout)this.jPanelRight.getLayout();
            layout.previous(jPanelRight);
        }
        for(Component comp : jPanelLeft.getComponents()){
            if(comp instanceof JButton)
            comp.setVisible(false);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnLogOut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAirBus1;
    private javax.swing.JCheckBox cbAirBus2;
    private javax.swing.JCheckBox cbAirBus3;
    private javax.swing.JCheckBox cbBoeing1;
    private javax.swing.JCheckBox cbBoeing2;
    private javax.swing.JCheckBox cbBoeing3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCheckBox;
    private javax.swing.JTextField txtAirlinerAddress;
    private javax.swing.JTextField txtAirlinerContactNo;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtAirlinerRating;
    private javax.swing.JTextField txtCountryOfOrigin;
    private javax.swing.JTextField txtTotalFlights;
    private javax.swing.JTextField txtYearOfEstablishment;
    // End of variables declaration//GEN-END:variables
}