/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Flight.Flight;
import Business.Flight.FlightDirectory;
import UserInterface.LoginScreen;
import UserInterface.SuccessScreen;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.ConcurrentModificationException;
import java.util.Iterator;
import java.util.concurrent.CopyOnWriteArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shahd
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlineJPanel
     */
    private JPanel jPanelRight;
    private AirlinerDirectory airlinerDirectory;
    private JPanel jPanelLeft;
    private FlightDirectory flightDir;
    public ManageAirlinerJPanel(JPanel jPanelRight, JPanel jPanelLeft,AirlinerDirectory airlinerDirectory, FlightDirectory flightDir) {
        this.jPanelRight = jPanelRight;
        this.airlinerDirectory = airlinerDirectory;
        this.jPanelLeft = jPanelLeft;
        this.flightDir = flightDir;
        initComponents();
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblManageAirliner.getModel();
        dtm.setRowCount(0);
        for(Airliner a : airlinerDirectory.getAirlinerDirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getAirlinerAddress();
            row[2] = a.getAirlinerContactNumber();
            row[3] = a.getTotalFlightsPerDay();
            row[4] = a.getAirlinerRating();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAirliner = new javax.swing.JButton();
        btnCreateAirliner = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDeleteAirliner = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblManageAirliner = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        btnViewAirliner.setText("View Airliner");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnCreateAirliner.setText("Create New Airliner");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Airliner Details");

        btnDeleteAirliner.setText("Delete Airliner");
        btnDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlinerActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel2.setText("admin");

        tblManageAirliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Airliner Address", "Airliner Contact No.", "Total No. of Flights per Day", "Airliner Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblManageAirliner);
        if (tblManageAirliner.getColumnModel().getColumnCount() > 0) {
            tblManageAirliner.getColumnModel().getColumn(0).setResizable(false);
            tblManageAirliner.getColumnModel().getColumn(1).setResizable(false);
            tblManageAirliner.getColumnModel().getColumn(2).setResizable(false);
            tblManageAirliner.getColumnModel().getColumn(3).setResizable(false);
            tblManageAirliner.getColumnModel().getColumn(4).setResizable(false);
        }

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnCreateAirliner)
                        .addGap(30, 30, 30)
                        .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)jPanelRight.getLayout();
        jPanelRight.add(new CreateAirlinerJPanel(jPanelRight,jPanelLeft, airlinerDirectory));
        layout.next(jPanelRight);
        
       
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliner.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select an Airliner","Warning", JOptionPane.WARNING_MESSAGE);
        } else{
            CardLayout layout = (CardLayout)jPanelRight.getLayout();
            Airliner airliner = (Airliner) tblManageAirliner.getValueAt(selectedRow, 0);
            jPanelRight.add(new ViewAirlinerJPanel(jPanelRight,jPanelLeft, airliner));
            layout.next(jPanelRight);
        }

    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    public void deleteFlights(Airliner airliner){
        System.out.println("in delete");
        
        ArrayList<Flight> temp = new ArrayList<Flight>();
        for(Flight f : flightDir.getFlightList()){
            if(f.getAirlinerName().getAirlinerName().equals(airliner.getAirlinerName())){
                temp.add(f);
            }
        }
        flightDir.getFlightList().removeAll(temp);
//     
    }
    
    private void btnDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliner.getSelectedRow();
        System.out.println(selectedRow);
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select an Airliner","Warning", JOptionPane.WARNING_MESSAGE);
        } else{
            boolean flag = false;
            Airliner airliner = (Airliner) tblManageAirliner.getValueAt(selectedRow, 0);
            for(Flight f : flightDir.getFlightList()){
               if(f.getAirlinerName().getAirlinerName().equals(airliner.getAirlinerName())){
                   flag = true;
                   int dialogButton = JOptionPane.YES_NO_OPTION;
                   int dialogResult = JOptionPane.showConfirmDialog(null, "Flights are scheduled for this airliner. \nThis will delete the flights.\nDo you wish to continue?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    deleteFlights(airliner);
                    airlinerDirectory.deleteAirliner(airliner);
                    JOptionPane.showMessageDialog(null, "Airliner deleted successfully!","Information", JOptionPane.INFORMATION_MESSAGE);
                    populateTable();
                    break;
            }
               } 
            }
            if(flag == false){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the Airliner?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                airlinerDirectory.deleteAirliner(airliner);
                JOptionPane.showMessageDialog(null, "Airliner deleted successfully!","Information", JOptionPane.INFORMATION_MESSAGE);
                populateTable();
            }
            }
        }
    }//GEN-LAST:event_btnDeleteAirlinerActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
       for(Component comp : jPanelRight.getComponents()){
            if(comp instanceof LoginScreen){
                
            } else{
                jPanelRight.remove(comp);
            }
            CardLayout layout = (CardLayout)this.jPanelRight.getLayout();
            layout.previous(jPanelRight);
        }
        for(Component comp : jPanelLeft.getComponents()){
            if(comp instanceof JButton)
                comp.setVisible(false);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        jPanelRight.remove(this);
        CardLayout layout = (CardLayout)this.jPanelRight.getLayout();
        layout.previous(jPanelRight);
        System.out.println("last component: "+jPanelRight.getComponent(jPanelRight.getComponentCount()-1));
       
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnDeleteAirliner;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblManageAirliner;
    // End of variables declaration//GEN-END:variables
}
